### ISSUE TITLE
i have an issue with your website

### ISSUE THREAD

**Issue by m1-t** [al1ce4k/site#7]
when i went to your website thousands of men in black ski masks broke into my home and kidnapped me and stabbed me nine times in the chest. i dontn know why you would do this to me. but u did. i'll neveer forgive you.. FREAK

https://github.com/user-attachments/assets/4ccef464-6b7b-47ee-85cb-a334a66396c2

**Comment by al1ce4k** [comment]
i fixed it

**Comment by nxtkallax** [comment]
no
